"""Add creator and editor info to Question model

Revision ID: 7febe06add03
Revises: 
Create Date: 2024-05-25 14:35:05.675590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7febe06add03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('last_edited_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_edited_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('last_edited_at')
        batch_op.drop_column('last_edited_by')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
