"""empty message

Revision ID: 92c3bb4e699d
Revises: 06ebbbccc0dc
Create Date: 2024-05-26 17:10:08.999027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c3bb4e699d'
down_revision = '06ebbbccc0dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubric', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubric', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###
