"""Add Rubric model

Revision ID: e3b99fa74e63
Revises: 7febe06add03
Create Date: 2024-05-25 17:06:37.293080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e3b99fa74e63'
down_revision = '7febe06add03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubric', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('question_types', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('sections', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('difficulty_levels', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('coverage', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('time_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('randomization', sa.Boolean(), nullable=True))
        batch_op.drop_column('blueprint')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubric', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blueprint', sqlite.JSON(), nullable=True))
        batch_op.drop_column('randomization')
        batch_op.drop_column('time_limit')
        batch_op.drop_column('coverage')
        batch_op.drop_column('difficulty_levels')
        batch_op.drop_column('sections')
        batch_op.drop_column('question_types')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
